#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#regarding the 'off' issue of spring.main.banner-mode please have a look at https://github.com/spring-projects/spring-boot/commit/43b8e65eee7c23a7f7c3b61f8a436dc9cbfe5b96
server: 
  port: 8081
  servlet:
    context-path: /judicialwarrant
    path: /api
    
app:
  default-password-length: 6
  moj-ou-id: 1
  security:
    activedirectory:
      domain: ou=jw,dc=oman,dc=local
      url: ldap://192.168.0.41:389/
      admin:
        username: CN=JW Supper Admin,OU=JW,DC=oman,DC=local
        password: P@ssw0rd
    basicauthentication:
      realm-name: Oman MOJ Judicial Warrant
    max-inactive-interval: 12000
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: judicialwarrant
    password: oracle
    pool-properties:
      initial-size: 30
      max-active: 10
  ucm:
    ip: 192.168.0.83
    port: 4444
    username: weblogic
    password: P@ssw0rd    

   
spring:
  mail:
   host: mail.informatique-eg.com
   port: 25
   username: attabdullah@informatique-eg.com
   password: "#$AaPw57"
   protocol: smtp
   test-connection: true
   properties:
      mail:
        smtp:
          auth: true 
          from: attabdullah@informatique-eg.com
        debug: false
  


   


              