
 #https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#regarding the 'off' issue of spring.main.banner-mode please have a look at https://github.com/spring-projects/spring-boot/commit/43b8e65eee7c23a7f7c3b61f8a436dc9cbfe5b96

app:
  defaultpasswordlength: 3 
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: judicialwarrant
    password: oracle
    pool-properties:
      initial-size: 30
      max-active: 10
        
  security:
    activedirectory:
      domain: ou=jw,dc=oman,dc=local
      url: ldap://192.168.0.41:389/
      username: cn=administrator,cn=users,dc=oman,dc=local
      password: P@ssw0rd@
    basicauthentication:
      realm-name: Oman MOJ Judicial Warrant
    max-inactive-interval: 12000    
   
      
server: 
  port: 8081
  servlet:
    context-path: /judicialwarrant
    path: /api
   
spring:
  main:
    banner-mode: 'off'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          batch-size: 20
  profiles:
    active: dev
  mail:
   host: smtp.gmail.com
   port: 587
   username: attiaelsady@gmail.com
   password: attia123/
   protocol: smtp
   tls: true
   test-connection: false
   properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
    
    
     
ucm:
  ip: 192.168.0.44
  port: 4444
  username: weblogic
  password: welcome1     

   


              