ALTER TABLE REQUEST_TYPE RENAME COLUMN REQUEST_NUMBER_PREFIX TO REQUEST_SERIAL_PREFIX;

CREATE TABLE REQUEST_INTERNAL_STATUS 
(
  ID NUMBER(2, 0) NOT NULL 
, CODE VARCHAR2(50 BYTE) NOT NULL 
, ARABIC_NAME VARCHAR2(100 BYTE) NOT NULL 
, ENGLISH_NAME VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT REQUEST_INTERNAL_STATUS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE REQUEST_INTERNAL_STATUS
ADD CONSTRAINT REQUEST_INTERNAL_STATUS_UK1 UNIQUE 
(
  CODE 
)
ENABLE;

ALTER TABLE REQUEST 
ADD (CURRENT_INTERNAL_STATUS_ID NUMBER );

alter table REQUEST
  add constraint REQUEST_REQUEST_STATUS_FK foreign key (CURRENT_STATUS_ID)
  references REQUEST_STATUS (ID);
  
  ALTER TABLE REQUEST
ADD CONSTRAINT REQUEST_INTERNAL_STATUS_FK1 FOREIGN KEY
(
  CURRENT_INTERNAL_STATUS_ID 
)
REFERENCES REQUEST_INTERNAL_STATUS
(
  ID 
)
ENABLE;


ALTER TABLE REQUEST_HISTORY_LOG 
ADD (INTERNAL_STATUS_ID NUMBER );

ALTER TABLE REQUEST_HISTORY_LOG  
MODIFY (INTERNAL_STATUS_ID NULL);


alter table REQUEST_HISTORY_LOG
  add constraint RQST_HSTRY_RQST_STS_FK foreign key (REQUEST_STATUS_ID)
  references REQUEST_STATUS (ID);

  ALTER TABLE REQUEST_HISTORY_LOG
ADD CONSTRAINT RQST_HSTRY_RQST_INT_STS_FK FOREIGN KEY
(
  INTERNAL_STATUS_ID 
)
REFERENCES REQUEST_INTERNAL_STATUS
(
  ID 
)
ENABLE;


CREATE TABLE NATIONALITY 
(
  ID NUMBER(4) NOT NULL 
, ARABIC_NAME VARCHAR2(20) NOT NULL 
, ENGLISH_NAME VARCHAR2(20) NOT NULL 
, CODE VARCHAR2(3) NOT NULL 
, ISO NUMBER(3, 0) NOT NULL
, CONSTRAINT NATIONALITY_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

alter table NATIONALITY
  add constraint NATIONALITY_CODE unique (CODE);
alter table NATIONALITY
  add constraint NATIONALITY_ISO unique (ISO);

  
  CREATE TABLE REQUEST_SERIAL 
(
  ID NUMBER NOT NULL 
, LAST_NUMBER NUMBER(5) NOT NULL 
, YEAR NUMBER NOT NULL 
, VERSION NUMBER NOT NULL 
, REQUEST_TYPE_ID NUMBER(2, 0) NOT NULL
, CONSTRAINT REQUEST_SERIAL_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE REQUEST_SERIAL
ADD CONSTRAINT REQUEST_TYPE_FK1 FOREIGN KEY
(
  REQUEST_TYPE_ID 
)
REFERENCES REQUEST_TYPE
(
  ID 
)
ENABLE;


CREATE TABLE JWCD_REQUEST 
(
  ID NUMBER NOT NULL 
, JOB_TITLE VARCHAR2(300) NOT NULL 
);

ALTER TABLE JWCD_REQUEST
ADD CONSTRAINT JWCD_REQUEST_PK PRIMARY KEY 
(
  ID 
)
ENABLE;

ALTER TABLE JWCD_REQUEST
ADD CONSTRAINT JWCD_REQUEST_REQUEST_FK1 FOREIGN KEY
(
  ID 
)
REFERENCES REQUEST
(
  ID 
)
ENABLE;


CREATE SEQUENCE REQUEST_SERIAL_SEQ INCREMENT BY 1 start with 1 MAXVALUE 99999999999999999999 MINVALUE 1 CACHE 20;


ALTER TABLE APP_ROLE
  ADD LDAP_SECURITY_GROUP varchar2(50);
  
  alter table APP_USER
  add constraint USER_credientials_FK foreign key (ID)
  references APP_USER_CREDENTIALS (ID);